### ISSUE TITLE
Wand-config in comiple.sh on Debian

### ISSUE THREAD

**Issue by johannspies** [pulsar123/Macro-scripts#1]
On Debian I had to change line 8 to 

 gcc `/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.6/bin-q16/Wand-config --cflags --cppflags` -O4 -o deadpixels deadpixels.c `/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.6/bin-q16/Wand-config --ldflags --libs` -lm

to get it working.

**Comment by pulsar123** [comment]
This is a customization issue, closing.
